version: "3.3"
services:
  rabbit:
    image: "rabbitmq:3-management"
    environment:
      RABBITMQ_DEFAULT_USER: "rabbitmq"
      RABBITMQ_DEFAULT_PASS: "rabbitmq"
      RABBITMQ_DEFAULT_VHOST: "/"
    ports:
      - "15672:15672"
      - "5672:5672"
  order_service_db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: some_user
      POSTGRES_PASSWORD: some_password
